name = "Main"
version = "0.1.0"
defaultTargets = ["Main"]

[[lean_lib]]
name = "Main"
roots = ["Dirichlet", "Carlson", "StdSimplexMeasure", "Pochhammer", "SeveralComplexVariables"]
globs = [
  "StdSimplexMeasure", "StdSimplexMeasure.+",
  "Dirichlet", "Dirichlet.+",
  "Carlson", "Carlson.+",
  "Pochhammer", "Pochhammer.+",
  "SeveralComplexVariables", "SeveralComplexVariables.+",
]

[[lean_exe]]
name = "main"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.1"
