/-
Copyright (c) 2026 Bastiaan J Braams. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Bastiaan J Braams
-/
module

public import ComplexAnalysis.Runge.OpenSet
public import ComplexAnalysis.Cycle.ArgumentPrinciple
public import Mathlib.Analysis.Complex.LocallyUniformLimit

/-!
# The Mittag-Leffler theorem

Let `U` be open, `S ⊆ U` a set without accumulation points in `U`, and for each `a ∈ S` let
`P a` be a function holomorphic off `a` (a principal part). There is a function `f` holomorphic
on `U \ S` such that near every `a ∈ S` the difference `f - P a` extends holomorphically.

The proof follows Conway VIII.3.2: with the exhaustion of `U` by the hole-free hulls
`rungeHull U n (1 / (n + 1))`, the finitely many principal parts with poles in the `n`-th ring
are corrected by rational functions with poles outside `U` (Runge's theorem) so that the
corrections are bounded by `2⁻ⁿ` on the previous hull; the corrected series converges locally
uniformly on `U` minus the poles.

## Main results

* `Complex.mittagLeffler`: existence of a meromorphic function with prescribed principal parts.
* `Complex.differentiableOn_of_mem_adjoin_rungeGenerators`: rational functions with poles
  outside `U` are holomorphic on `U`.
-/

public noncomputable section

open Set Metric Filter Function
open scoped Topology

namespace Complex

/-- Elements of the algebra generated by the identity and the simple poles at points outside
`U` are holomorphic on `U`. -/
theorem differentiableOn_of_mem_adjoin_rungeGenerators {U : Set ℂ} {r : ℂ → ℂ}
    (hr : r ∈ Algebra.adjoin ℂ (rungeGenerators Uᶜ)) : DifferentiableOn ℂ r U := by
  induction hr using Algebra.adjoin_induction with
  | mem g hg =>
    rcases hg with rfl | ⟨a, ha, rfl⟩
    · exact differentiableOn_id
    · exact ((differentiableOn_const a).sub differentiableOn_id).inv fun z hz =>
        sub_ne_zero.mpr fun h => ha ((show a = z from h).symm ▸ hz)
  | algebraMap c => exact differentiableOn_const _
  | add x y _ _ hx hy => exact hx.add hy
  | mul x y _ _ hx hy => exact hx.mul hy

/-- The `n`-th hole-free hull of the standard exhaustion of `U`. -/
def mlHull (U : Set ℂ) (n : ℕ) : Set ℂ := rungeHull U n (1 / (n + 1))

theorem mlHull_mono {U : Set ℂ} {m n : ℕ} (h : m ≤ n) : mlHull U m ⊆ mlHull U n :=
  rungeHull_mono (by exact_mod_cast h)
    (one_div_le_one_div_of_le (by positivity) (by exact_mod_cast Nat.add_le_add_right h 1))

theorem isCompact_mlHull (U : Set ℂ) (n : ℕ) : IsCompact (mlHull U n) :=
  isCompact_rungeHull U n _

theorem mlHull_subset {U : Set ℂ} (n : ℕ) : mlHull U n ⊆ U :=
  rungeHull_subset (by positivity)

/-- Each hull lies in the interior of the next one. -/
theorem mlHull_subset_interior (U : Set ℂ) (n : ℕ) :
    mlHull U n ⊆ interior (mlHull U (n + 1)) := by
  intro z hz
  rw [mem_interior_iff_mem_nhds]
  set ρ : ℝ := 1 / ((n + 1) * (n + 2)) with hρ_def
  have hρ : 0 < ρ := by positivity
  have hρ1 : ρ ≤ 1 := by
    rw [hρ_def, div_le_one (by positivity)]
    nlinarith
  have hkey : (1 : ℝ) / (n + 1) - ρ = 1 / (n + 2) := by
    rw [hρ_def]
    field_simp
    ring
  filter_upwards [ball_mem_nhds z hρ] with z' hz'
  rw [mem_ball, dist_eq_norm] at hz'
  refine Set.mem_inter ?_ fun u hu => ?_
  · rw [mem_closedBall, dist_zero_right]
    have h1 : ‖z‖ ≤ n := by simpa using hz.1
    have h2 : ‖z'‖ ≤ ‖z‖ + ‖z' - z‖ := norm_le_norm_add_norm_sub' z' z
    push_cast
    linarith
  · have h1 := hz.2 u hu
    have h2 : dist z u ≤ dist z z' + dist z' u := dist_triangle z z' u
    have h3 : dist z z' = ‖z' - z‖ := by rw [dist_eq_norm, norm_sub_rev]
    have h4 : (1 : ℝ) / ((n + 1 : ℕ) + 1) = 1 / (n + 2) := by push_cast; ring
    rw [h4]
    linarith

/-- Every point of `U` lies in some hull. -/
theorem exists_mem_mlHull {U : Set ℂ} (hU : IsOpen U) {z : ℂ} (hz : z ∈ U) :
    ∃ n, z ∈ mlHull U n := by
  obtain ⟨m, hm⟩ := exists_forall_subset_rungeHull_nat hU isCompact_singleton
    (singleton_subset_iff.mpr hz)
  exact ⟨m, hm m le_rfl (mem_singleton z)⟩

/-- **The Mittag-Leffler theorem.** For a set `S` without accumulation points in the open set
`U` and principal parts `P a` holomorphic off `a`, there is a function holomorphic on `U \ S`
whose difference with `P a` extends holomorphically over each `a ∈ S`. -/
theorem mittagLeffler {U : Set ℂ} (hU : IsOpen U) {S : Set ℂ} (hSU : S ⊆ U)
    (hS : Sᶜ ∈ codiscreteWithin U) {P : ℂ → ℂ → ℂ}
    (hP : ∀ a ∈ S, DifferentiableOn ℂ (P a) {a}ᶜ) :
    ∃ f : ℂ → ℂ, DifferentiableOn ℂ f (U \ S) ∧
      ∀ a ∈ S, ∃ g : ℂ → ℂ, AnalyticAt ℂ g a ∧ f =ᶠ[𝓝[≠] a] fun z => P a z + g z := by
  classical
  -- discreteness of `S` in `U`
  have hSdisc : ∀ z ∈ U, ∀ᶠ w in 𝓝[≠] z, w ∉ S := by
    intro z hz
    rw [mem_codiscreteWithin] at hS
    filter_upwards [disjoint_principal_right.mp (hS z hz)] with w hw hwS
    exact hw ⟨hSU hwS, fun h => h hwS⟩
  have hopen' : ∀ a ∈ U, IsOpen (U \ (S \ {a})) := by
    intro a ha
    rw [isOpen_iff_mem_nhds]
    intro z hz
    have h1 := hSdisc z hz.1
    rw [eventually_nhdsWithin_iff] at h1
    filter_upwards [h1, hU.mem_nhds hz.1] with w hw hwU
    refine ⟨hwU, fun hwS => ?_⟩
    by_cases hwz : w = z
    · exact hz.2 (hwz ▸ hwS)
    · exact hw hwz hwS.1
  have hopenUS : IsOpen (U \ S) := by
    rw [isOpen_iff_mem_nhds]
    intro z hz
    have h1 := hSdisc z hz.1
    rw [eventually_nhdsWithin_iff] at h1
    filter_upwards [h1, hU.mem_nhds hz.1] with w hw hwU
    refine ⟨hwU, fun hwS => ?_⟩
    by_cases hwz : w = z
    · exact hz.2 (hwz ▸ hwS)
    · exact hw hwz hwS
  -- the exhaustion
  set K : ℕ → Set ℂ := mlHull U with hK_def
  have hKc : ∀ n, IsCompact (K n) := fun n => isCompact_mlHull U n
  have hKU : ∀ n, K n ⊆ U := fun n => mlHull_subset n
  have hKmono : ∀ {m n : ℕ}, m ≤ n → K m ⊆ K n := fun h => mlHull_mono h
  have hKint : ∀ n, K n ⊆ interior (K (n + 1)) := mlHull_subset_interior U
  have hfin : ∀ n, (K n ∩ S).Finite := fun n => by
    have := finite_diff_of_isCompact_of_mem_codiscreteWithin (hKc n) (hKU n) hS
    rwa [Set.sdiff_compl] at this
  -- the pieces of `S`
  set Tset : ℕ → Set ℂ := fun n => {a | a ∈ K n ∧ a ∈ S ∧ ∀ m < n, a ∉ K m} with hTset_def
  have hTfin : ∀ n, (Tset n).Finite := fun n => (hfin n).subset fun a ha => ⟨ha.1, ha.2.1⟩
  set T : ℕ → Finset ℂ := fun n => (hTfin n).toFinset with hT_def
  have hTmem : ∀ n a, a ∈ T n ↔ a ∈ K n ∧ a ∈ S ∧ ∀ m < n, a ∉ K m := fun n a => by
    simp only [T]
    rw [Set.Finite.mem_toFinset]
    rfl
  have hTS : ∀ n, (T n : Set ℂ) ⊆ S := fun n a ha => ((hTmem n a).mp ha).2.1
  have hTK : ∀ n a, a ∈ T n → ∀ m < n, a ∉ K m := fun n a ha => ((hTmem n a).mp ha).2.2
  have hTdisj : ∀ {m n : ℕ}, m ≠ n → ∀ a, a ∈ T m → a ∉ T n := by
    intro m n hmn a ham han
    rcases lt_or_gt_of_ne hmn with h | h
    · exact hTK n a han m h ((hTmem m a).mp ham).1
    · exact hTK m a ham n h ((hTmem n a).mp han).1
  -- the principal-part sums
  set F : ℕ → ℂ → ℂ := fun n z => ∑ a ∈ T n, P a z with hF_def
  have hFdiff : ∀ n, DifferentiableOn ℂ (F n) ((T n : Set ℂ))ᶜ := by
    intro n
    have : F n = ∑ a ∈ T n, P a := by
      ext z
      simp [F, Finset.sum_apply]
    rw [this]
    refine DifferentiableOn.sum fun a ha => (hP a (hTS n ha)).mono ?_
    intro z hz h
    exact hz (h ▸ ha)
  -- Runge corrections
  have hcorr : ∀ n, ∃ r ∈ Algebra.adjoin ℂ (rungeGenerators Uᶜ),
      ∀ z ∈ K n, ‖F (n + 1) z - r z‖ ≤ (1 / 2 : ℝ) ^ (n + 1) := by
    intro n
    have hopenT : IsOpen ((T (n + 1) : Set ℂ))ᶜ := (T (n + 1)).finite_toSet.isClosed.isOpen_compl
    have hKT : K n ⊆ ((T (n + 1) : Set ℂ))ᶜ := fun z hz hzT =>
      hTK (n + 1) z hzT n (Nat.lt_succ_self n) hz
    have hAK : Disjoint Uᶜ (K n) := disjoint_left.mpr fun a ha haK => ha (hKU n haK)
    have hA : ∀ w ∉ K n, Bornology.IsBounded (connectedComponentIn (K n)ᶜ w) →
        ∃ a ∈ Uᶜ, a ∈ connectedComponentIn (K n)ᶜ w := fun w hw hb =>
      exists_compl_mem_connectedComponentIn_rungeHull hw hb
    exact runge (hKc n) hAK hA hopenT hKT (hFdiff (n + 1)) _ (by positivity)
  choose r hr hrε using hcorr
  -- the terms of the series
  set r' : ℕ → ℂ → ℂ := fun n => Nat.casesOn n (fun _ => 0) (fun k => r k) with hr'_def
  have hr'0 : r' 0 = fun _ => 0 := rfl
  have hr'succ : ∀ k, r' (k + 1) = r k := fun k => rfl
  have hr'diff : ∀ n, DifferentiableOn ℂ (r' n) U := by
    intro n
    cases n with
    | zero => exact differentiableOn_const _
    | succ k => exact differentiableOn_of_mem_adjoin_rungeGenerators (hr k)
  set t : ℕ → ℂ → ℂ := fun n z => F n z - r' n z with ht_def
  have htdiff : ∀ n, DifferentiableOn ℂ (t n) (U \ (T n : Set ℂ)) := fun n =>
    ((hFdiff n).mono fun z hz => hz.2).sub ((hr'diff n).mono fun z hz => hz.1)
  have htbound : ∀ n z, n ≠ 0 → z ∈ K (n - 1) → ‖t n z‖ ≤ (1 / 2 : ℝ) ^ n := by
    intro n z hn hz
    obtain ⟨m, rfl⟩ := Nat.exists_eq_succ_of_ne_zero hn
    exact hrε m z hz
  have htbound' : ∀ m n z, z ∈ K m → m + 1 ≤ n → ‖t n z‖ ≤ (1 / 2 : ℝ) ^ n := by
    intro m n z hz hmn
    refine htbound n z (by omega) (hKmono ?_ hz)
    omega
  have hsummable : ∀ m z, z ∈ K m → Summable fun n => t n z := by
    intro m z hz
    refine Summable.of_norm_bounded_eventually summable_geometric_two ?_
    rw [Nat.cofinite_eq_atTop]
    filter_upwards [eventually_ge_atTop (m + 1)] with n hn
    exact htbound' m n z hz hn
  -- local holomorphy of series with these bounds
  have hloc : ∀ (s : ℕ → ℂ → ℂ) (V : Set ℂ) (m : ℕ), IsOpen V → V ⊆ K m →
      (∀ n z, z ∈ V → m + 1 ≤ n → ‖s n z‖ ≤ (1 / 2 : ℝ) ^ n) →
      (∀ n, DifferentiableOn ℂ (s n) V) →
      DifferentiableOn ℂ (fun z => ∑' n, s n z) V := by
    intro s V m hV hVK hbound hdiff
    have hsum : ∀ z ∈ V, Summable fun n => s n z := by
      intro z hz
      refine Summable.of_norm_bounded_eventually summable_geometric_two ?_
      rw [Nat.cofinite_eq_atTop]
      filter_upwards [eventually_ge_atTop (m + 1)] with n hn
      exact hbound n z hz hn
    have htail : DifferentiableOn ℂ (fun z => ∑' n, s (n + (m + 1)) z) V := by
      refine Complex.differentiableOn_tsum_of_summable_norm
        (u := fun n => (1 / 2 : ℝ) ^ (n + (m + 1))) ?_ (fun n => hdiff (n + (m + 1))) hV ?_
      · exact (summable_geometric_two.comp_injective (add_left_injective (m + 1)))
      · intro n z hz
        exact hbound (n + (m + 1)) z hz (by omega)
    have hhead : DifferentiableOn ℂ (fun z => ∑ n ∈ Finset.range (m + 1), s n z) V := by
      have : (fun z => ∑ n ∈ Finset.range (m + 1), s n z) = ∑ n ∈ Finset.range (m + 1), s n := by
        ext z
        simp [Finset.sum_apply]
      rw [this]
      exact DifferentiableOn.sum fun n _ => hdiff n
    refine (hhead.add htail).congr fun z hz => ?_
    exact ((hsum z hz).sum_add_tsum_nat_add (m + 1)).symm
  refine ⟨fun z => ∑' n, t n z, ?_, ?_⟩
  · -- holomorphy off `S`
    intro z hz
    obtain ⟨m, hm⟩ := exists_mem_mlHull hU hz.1
    set V : Set ℂ := interior (K (m + 1)) ∩ (U \ S) with hV_def
    have hVo : IsOpen V := isOpen_interior.inter hopenUS
    have hzV : z ∈ V := ⟨hKint m hm, hz⟩
    have hVK : V ⊆ K (m + 1) := fun w hw => interior_subset hw.1
    have hdiff : ∀ n, DifferentiableOn ℂ (t n) V := fun n =>
      (htdiff n).mono fun w hw => ⟨hw.2.1, fun h => hw.2.2 (hTS n h)⟩
    exact ((hloc t V (m + 1) hVo hVK (fun n w hw hn => htbound' (m + 1) n w (hVK hw) hn) hdiff)
      z hzV).differentiableAt (hVo.mem_nhds hzV) |>.differentiableWithinAt
  · -- the principal part at `a ∈ S`
    intro a ha
    have haU : a ∈ U := hSU ha
    have hex : ∃ n, a ∈ K n := exists_mem_mlHull hU haU
    obtain ⟨m, hamK, hamin⟩ : ∃ m, a ∈ K m ∧ ∀ k < m, a ∉ K k :=
      ⟨Nat.find hex, Nat.find_spec hex, fun k hk => Nat.find_min hex hk⟩
    have haT : a ∈ T m := (hTmem m a).mpr ⟨hamK, ha, hamin⟩
    set t' : ℕ → ℂ → ℂ := fun n z => if n = m then 0 else t n z with ht'_def
    set g : ℂ → ℂ := fun z => (∑ b ∈ (T m).erase a, P b z - r' m z) + ∑' n, t' n z with hg_def
    refine ⟨g, ?_, ?_⟩
    · -- analyticity of `g` at `a`
      set V : Set ℂ := interior (K (m + 1)) ∩ (U \ (S \ {a})) with hV_def
      have hVo : IsOpen V := isOpen_interior.inter (hopen' a haU)
      have haV : a ∈ V := ⟨hKint m hamK, haU, fun h => h.2 rfl⟩
      have hVK : V ⊆ K (m + 1) := fun w hw => interior_subset hw.1
      have hVU : V ⊆ U := fun w hw => hw.2.1
      have h1 : DifferentiableOn ℂ (fun z => ∑ b ∈ (T m).erase a, P b z) V := by
        have : (fun z => ∑ b ∈ (T m).erase a, P b z) = ∑ b ∈ (T m).erase a, P b := by
          ext z
          simp [Finset.sum_apply]
        rw [this]
        refine DifferentiableOn.sum fun b hb => ?_
        have hbS : b ∈ S := hTS m (Finset.mem_of_mem_erase hb)
        have hba : b ≠ a := Finset.ne_of_mem_erase hb
        refine (hP b hbS).mono fun w hw hwb => ?_
        have hwb' : w = b := hwb
        exact hw.2.2 ⟨hwb'.symm ▸ hbS, fun hwa => hba (hwb'.symm.trans hwa)⟩
      have h2 : DifferentiableOn ℂ (r' m) V := (hr'diff m).mono hVU
      have hdiff' : ∀ n, DifferentiableOn ℂ (t' n) V := by
        intro n
        by_cases hn : n = m
        · simp only [t', hn, ite_true]
          exact differentiableOn_const _
        · simp only [t', hn, ite_false]
          refine (htdiff n).mono fun w hw => ⟨hw.2.1, fun hwT => ?_⟩
          exact hw.2.2 ⟨hTS n hwT, fun hwa => hTdisj (Ne.symm hn) a haT
            ((show w = a from hwa) ▸ hwT)⟩
      have hbound' : ∀ n z, z ∈ V → m + 1 + 1 ≤ n → ‖t' n z‖ ≤ (1 / 2 : ℝ) ^ n := by
        intro n z hz hn
        have hnm : n ≠ m := by omega
        simp only [t', hnm, ite_false]
        exact htbound' (m + 1) n z (hVK hz) hn
      have h3 := hloc t' V (m + 1) hVo hVK hbound' hdiff'
      have hg : DifferentiableOn ℂ g V := (h1.sub h2).add h3
      exact DifferentiableOn.analyticAt hg (hVo.mem_nhds haV)
    · -- the germ identity
      have hev : ∀ᶠ z in 𝓝[≠] a, z ∈ U ∧ z ∉ S := by
        filter_upwards [hSdisc a haU, nhdsWithin_le_nhds (hU.mem_nhds haU)] with z hzS hzU
        exact ⟨hzU, hzS⟩
      filter_upwards [hev] with z hz
      obtain ⟨k, hk⟩ := exists_mem_mlHull hU hz.1
      have hsum := hsummable k z hk
      rw [hsum.tsum_eq_add_tsum_ite m]
      have htm : t m z = P a z + (∑ b ∈ (T m).erase a, P b z - r' m z) := by
        simp only [t, F]
        rw [← Finset.add_sum_erase _ _ haT]
        ring
      rw [htm]
      simp only [g, t']
      ring

end Complex

end
