/-
Copyright (c) 2026 Bastiaan J Braams. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Bastiaan J Braams
-/
module

public import Mathlib.LinearAlgebra.Matrix.ToLinearEquiv
public import Mathlib.RingTheory.Polynomial.Resultant.Basic
public import SeveralComplexVariables.AnalyticGerm.Fiber
public import SeveralComplexVariables.AnalyticGerm.Weierstrass

/-!
# Elimination of the scalar variable for relatively prime germs

A distinguished polynomial and a relatively prime polynomial germ have nonzero resultant. The
proof uses Weierstrass division to show injectivity of the Sylvester map. Its adjugate then
supplies a nonzero parameter germ in the generated ideal.

## Main results

`resultant_ne_zero_of_isRelPrime_polynomialHom` is nonvanishing of the resultant of a
distinguished polynomial and a relatively prime polynomial germ.
`exists_base_combination_of_isRelPrime` produces a nonzero parameter germ in the generated
ideal. `sylvesterMap_injective_of_isRelPrime` is injectivity of the Sylvester map.
-/

public noncomputable section

open Polynomial

namespace SeveralComplexVariables.AnalyticGerm

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℂ E] [FiniteDimensional ℂ E]

/-- A polynomial of smaller degree divisible as a germ by a distinguished polynomial is zero. -/
theorem eq_zero_of_degree_lt_of_polynomialHom_dvd
    {p w : Polynomial (AnalyticGerm ℂ (0 : E))}
    (hw : w.IsDistinguishedAt (IsLocalRing.maximalIdeal _))
    (hdeg : p.degree < (w.natDegree : WithBot ℕ))
    (hdiv : polynomialHom w ∣ polynomialHom p) : p = 0 := by
  obtain ⟨q, hq⟩ := hdiv
  obtain ⟨r, hr⟩ := exists_polynomial_quotient p w hw q (by rw [hq, mul_comm])
  have hd : w ∣ p := ⟨r, polynomialHom_injective (by rw [map_mul, hr, hq])⟩
  by_contra hp
  have := Polynomial.degree_le_of_dvd hd hp
  rw [Polynomial.degree_eq_natDegree hw.monic.ne_zero] at this
  exact (not_lt_of_ge this) hdeg

/-- Relative primality of the germs makes the Sylvester map injective. -/
private theorem sylvesterMap_injective_of_isRelPrime
    {w p : Polynomial (AnalyticGerm ℂ (0 : E))}
    (hw : w.IsDistinguishedAt (IsLocalRing.maximalIdeal _))
    (hrel : IsRelPrime (polynomialHom w) (polynomialHom p)) :
    Function.Injective (Polynomial.sylvesterMap w p le_rfl le_rfl) := by
  apply (injective_iff_map_eq_zero _).mpr
  intro q hq
  have he : w * q.2.val + p * q.1.val = 0 := congrArg Subtype.val hq
  have he' : polynomialHom w * polynomialHom q.2.val +
      polynomialHom p * polynomialHom q.1.val = 0 := by
    simpa only [map_add, map_mul, map_zero] using congrArg polynomialHom he
  have hd : polynomialHom w ∣ polynomialHom q.1.val :=
    hrel.dvd_of_dvd_mul_left ⟨-polynomialHom q.2.val, by linear_combination he'⟩
  have hq1 : q.1.val = 0 := eq_zero_of_degree_lt_of_polynomialHom_dvd hw
    (Polynomial.mem_degreeLT.mp q.1.property) hd
  have hq2 : q.2.val = 0 := by
    simpa only [hq1, mul_zero, add_zero, mul_eq_zero, hw.monic.ne_zero, false_or] using he
  exact Prod.ext (Subtype.ext hq1) (Subtype.ext hq2)

/-- A distinguished polynomial relatively prime to another polynomial as an analytic germ has
nonzero resultant in the parameter germ ring. -/
theorem resultant_ne_zero_of_isRelPrime_polynomialHom
    {w p : Polynomial (AnalyticGerm ℂ (0 : E))}
    (hw : w.IsDistinguishedAt (IsLocalRing.maximalIdeal _))
    (hrel : IsRelPrime (polynomialHom w) (polynomialHom p)) : w.resultant p ≠ 0 := by
  let R := AnalyticGerm ℂ (0 : E)
  let T := Polynomial.sylvesterMap w p le_rfl le_rfl
  let b₁ := ((Polynomial.degreeLT.basis R w.natDegree).prod
    (Polynomial.degreeLT.basis R p.natDegree)).reindex finSumFinEquiv
  let b₂ := Polynomial.degreeLT.basis R (w.natDegree + p.natDegree)
  have hM : T.toMatrix b₁ b₂ = Polynomial.sylvester w p w.natDegree p.natDegree :=
    Polynomial.toMatrix_sylvesterMap' w p le_rfl le_rfl
  intro hz
  obtain ⟨v, hv, hMv⟩ := Matrix.exists_mulVec_eq_zero_iff.mpr hz
  let q := b₁.equivFun.symm v
  have hrepr : (b₁.repr q : Fin (w.natDegree + p.natDegree) → R) = v :=
    b₁.equivFun.apply_symm_apply v
  have hTq : T q = 0 := by
    apply b₂.equivFun.injective
    change (b₂.repr (T q) : Fin (w.natDegree + p.natDegree) → R) = b₂.equivFun 0
    rw [← T.toMatrix_mulVec_repr b₁ b₂ q, hM, hrepr, hMv, map_zero]
  have hq : q = 0 := (sylvesterMap_injective_of_isRelPrime hw hrel) (hTq.trans (map_zero T).symm)
  exact hv (by rw [← hrepr, hq, map_zero]; rfl)

/-- Eliminating the scalar variable puts a nonzero parameter germ in the ideal generated by two
relatively prime germs, the first of finite order in the scalar variable. -/
theorem exists_base_combination_of_isRelPrime
    {f g : AnalyticGerm ℂ (0 : E × ℂ)} {d : ℕ} (hd : orderInLastVariable f = d)
    (hrel : IsRelPrime f g) :
    ∃ h : AnalyticGerm ℂ (0 : E), h ≠ 0 ∧
      ∃ a b : AnalyticGerm ℂ (0 : E × ℂ), basePullback 0 h = a * f + b * g := by
  obtain ⟨⟨u, w⟩, ⟨hw, _, hfact⟩, _⟩ := existsUnique_preparation f hd
  have hrel' : IsRelPrime (polynomialHom w) g := by
    rw [hfact] at hrel
    exact hrel.of_mul_left_right
  by_cases hw0 : w.natDegree = 0
  · have hw1 : w = 1 := Polynomial.eq_one_of_monic_natDegree_zero hw.monic hw0
    refine ⟨1, one_ne_zero, ↑u⁻¹, 0, ?_⟩
    simp [hfact, hw1]
  obtain ⟨⟨q, p⟩, ⟨_, hdiv⟩, _⟩ := existsUnique_division w hw g
  have hwp : IsRelPrime (polynomialHom w) (polynomialHom p) := by
    rw [hdiv] at hrel'
    exact hrel'.of_mul_add_right_right
  have hres := resultant_ne_zero_of_isRelPrime_polynomialHom hw hwp
  obtain ⟨a, b, _, _, hab⟩ := Polynomial.exists_mul_add_mul_eq_C_resultant
    w p le_rfl le_rfl (Or.inl hw0)
  have hcomb : basePullback 0 (w.resultant p) =
      polynomialHom w * polynomialHom a + polynomialHom p * polynomialHom b := by
    simpa only [map_add, map_mul, polynomialHom_C, parameterHom, basePullback] using
      (congrArg polynomialHom hab).symm
  refine ⟨w.resultant p, hres, ↑u⁻¹ * (polynomialHom a - q * polynomialHom b),
    polynomialHom b, ?_⟩
  rw [hcomb, hfact, hdiv]
  have hu : (↑u⁻¹ : AnalyticGerm ℂ (0 : E × ℂ)) * ↑u = 1 := u.inv_val
  linear_combination -(polynomialHom a - q * polynomialHom b) * polynomialHom w * hu

end SeveralComplexVariables.AnalyticGerm
