/-
Copyright (c) 2026 Bastiaan J Braams. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Bastiaan J Braams
-/
module

public import ComplexAnalysis.Runge.Basic
public import ComplexAnalysis.Runge.PolePushing

/-!
# Runge's approximation theorem

A function holomorphic on a neighborhood of a compact set `K` is uniformly approximable on `K`
by rational functions whose poles lie in a prescribed set `A` meeting every bounded component
of the complement of `K`, together with polynomials. The rational functions are the elements of
the subalgebra of functions generated by the identity and the simple poles `(a - z)⁻¹`, `a ∈ A`.
When the complement of `K` is connected, polynomials suffice.

The proof combines the representation of `f` by finite sums of simple poles off `K`
(`Complex.exists_finset_pole_approx`) with pole pushing inside the components of the
complement (`Complex.UniformApproxOn.inv_sub_of_isPreconnected`) and the expansion of far
poles in polynomials (`Complex.UniformApproxOn.inv_sub_of_norm_gt`).

## Main results

* `Complex.runge`: Runge's theorem with poles in a prescribed set.
* `Complex.exists_polynomial_approx_of_isPreconnected_compl`: polynomial approximation when
  the complement of `K` is connected.

## References

* J. B. Conway, *Functions of One Complex Variable I*, Theorem VIII.1.7 and Corollary VIII.1.8.
* B. Simon, *Basic Complex Analysis*, Theorems 4.7.1 and 4.7.3.
-/

@[expose] public noncomputable section

open Set Metric Filter

namespace Complex

/-- The generators of the algebra of rational functions with poles in `A` and polynomials:
the identity and the simple poles `(a - z)⁻¹` for `a ∈ A`. -/
def rungeGenerators (A : Set ℂ) : Set (ℂ → ℂ) :=
  insert (fun z => z) ((fun a => fun z : ℂ => (a - z)⁻¹) '' A)

/-- The generators are continuous on a set disjoint from the poles. -/
theorem continuousOn_rungeGenerators {K A : Set ℂ} (hAK : Disjoint A K) :
    ∀ g ∈ rungeGenerators A, ContinuousOn g K := by
  rintro g (rfl | ⟨a, ha, rfl⟩)
  · exact continuousOn_id
  · exact (continuousOn_const.sub continuousOn_id).inv₀ fun z hz =>
      sub_ne_zero.mpr fun h => hAK.notMem_of_mem_left ha ((show a = z from h) ▸ hz)

/-- **Runge's theorem.** Let `K` be compact and `A` a set disjoint from `K` that meets every
bounded component of the complement of `K`. Every function holomorphic on an open neighborhood
of `K` is uniformly approximable on `K` by the elements of the algebra generated by the
identity and the simple poles with poles in `A`. -/
theorem runge {K : Set ℂ} (hK : IsCompact K) {A : Set ℂ} (hAK : Disjoint A K)
    (hA : ∀ w ∉ K, Bornology.IsBounded (connectedComponentIn Kᶜ w) →
      ∃ a ∈ A, a ∈ connectedComponentIn Kᶜ w)
    {U : Set ℂ} (hU : IsOpen U) (hKU : K ⊆ U) {f : ℂ → ℂ} (hf : DifferentiableOn ℂ f U) :
    UniformApproxOn K (Algebra.adjoin ℂ (rungeGenerators A)) f := by
  set S : Subalgebra ℂ (ℂ → ℂ) := Algebra.adjoin ℂ (rungeGenerators A) with hS_def
  have hS : ∀ r ∈ S, ContinuousOn r K := fun r hr =>
    continuousOn_of_mem_adjoin (continuousOn_rungeGenerators hAK) hr
  have hid : (fun z : ℂ => z) ∈ S := Algebra.subset_adjoin (mem_insert _ _)
  obtain ⟨R, hR⟩ := hK.isBounded.subset_closedBall 0
  have hR0 : 0 ≤ max R 0 := le_max_right _ _
  have hKR : K ⊆ closedBall 0 (max R 0) :=
    hR.trans (closedBall_subset_closedBall (le_max_left _ _))
  have hpole : ∀ c, c ∉ K → UniformApproxOn K S (fun z => (c - z)⁻¹) := by
    intro c hc
    set W : Set ℂ := connectedComponentIn Kᶜ c with hW_def
    have hWc : IsPreconnected W := isPreconnected_connectedComponentIn
    have hWK : Disjoint W K := disjoint_left.mpr fun w hw => connectedComponentIn_subset _ _ hw
    have hcW : c ∈ W := mem_connectedComponentIn hc
    by_cases hb : Bornology.IsBounded W
    · obtain ⟨a, haA, haW⟩ := hA c hc hb
      exact UniformApproxOn.inv_sub_of_isPreconnected S hK hS hWc hWK haW
        (UniformApproxOn.of_mem (Algebra.subset_adjoin (mem_insert_of_mem _ ⟨a, haA, rfl⟩))) hcW
    · obtain ⟨a, haW, haR⟩ : ∃ a ∈ W, max R 0 < ‖a‖ := by
        by_contra h
        push Not at h
        exact hb ((Metric.isBounded_iff_subset_closedBall 0).mpr
          ⟨max R 0, fun a ha => by simpa using h a ha⟩)
      exact UniformApproxOn.inv_sub_of_isPreconnected S hK hS hWc hWK haW
        (UniformApproxOn.inv_sub_of_norm_gt S hK hS hid hR0 hKR haR) hcW
  apply UniformApproxOn.of_forall_exists
  intro ε hε
  obtain ⟨n, c, a, hc, happrox⟩ := exists_finset_pole_approx hK hU hKU hf hε
  refine ⟨fun z => ∑ i, a i * (c i - z)⁻¹, ?_, happrox⟩
  have heq : (fun z => ∑ i, a i * (c i - z)⁻¹) = ∑ i, a i • (fun z => (c i - z)⁻¹) := by
    ext z
    simp [Finset.sum_apply, smul_eq_mul]
  rw [heq]
  exact UniformApproxOn.finsetSum S _ fun i _ => UniformApproxOn.smul S _ (hpole (c i) (hc i).2)

/-- **Polynomial approximation.** If the complement of the compact set `K` is connected, every
function holomorphic on an open neighborhood of `K` is uniformly approximable on `K` by
polynomials. -/
theorem exists_polynomial_approx_of_isPreconnected_compl {K : Set ℂ} (hK : IsCompact K)
    (hKc : IsPreconnected Kᶜ) {U : Set ℂ} (hU : IsOpen U) (hKU : K ⊆ U)
    {f : ℂ → ℂ} (hf : DifferentiableOn ℂ f U) {ε : ℝ} (hε : 0 < ε) :
    ∃ p : Polynomial ℂ, ∀ z ∈ K, ‖f z - p.eval z‖ ≤ ε := by
  have hA : ∀ w ∉ K, Bornology.IsBounded (connectedComponentIn Kᶜ w) →
      ∃ a ∈ (∅ : Set ℂ), a ∈ connectedComponentIn Kᶜ w := by
    intro w hw hb
    exfalso
    rw [hKc.connectedComponentIn hw] at hb
    have huniv : Bornology.IsBounded (univ : Set ℂ) := by
      rw [← compl_union_self K]
      exact hb.union hK.isBounded
    exact NormedSpace.unbounded_univ ℝ ℂ huniv
  obtain ⟨r, hr, hrε⟩ := runge hK (empty_disjoint K) hA hU hKU hf ε hε
  have hgen : rungeGenerators ∅ = {fun z : ℂ => z} := by
    simp [rungeGenerators]
  rw [SetLike.mem_coe, hgen, Algebra.adjoin_singleton_eq_range_aeval, AlgHom.mem_range] at hr
  obtain ⟨p, hp⟩ := hr
  refine ⟨p, fun z hz => ?_⟩
  have := hrε z hz
  rwa [← hp, Polynomial.aeval_fn_apply, Polynomial.coe_aeval_eq_eval] at this

end Complex

end
